Move the sketch.proto from the CMMS-api repo to anysketch.
world-federation-of-advertisers/any-sketch pull request #5
Opened 2021-04-13 23:27 UTC by wangyaopw

This file is copied from
https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c257ae4f0790d5080875edf80f536c4ae422ee19/src/main/proto/wfa/measurement/api/v2alpha/sketch.proto

The sketchConfig is acutally an anysketch concept. In CMMS, we use
protocol specific config + bytes to denote a sketch. Moving the
sketchproto into anysketch makes the ansketch repo a leaf repo.

The EncryptedSketch.proto and Sketch.proto inside CMMS-api would be
deleted.

2021-04-13 23:58 UTC, SanjayVas requested changes
> The EncryptedSketch.proto and Sketch.proto inside CMMS-api would be
> deleted.

encrypted_sketch.proto will still exists in the CMMS API repo as it documents the byte encoding of an encrypted sketch that's used by the API. (The message itself is never used and only consists of a single `bytes` field).

> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/5#-:-MYCeLhf7ZhsfuURKtaL:b-6c388q)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @wangyaopw)

___
*[src/main/proto/wfa/any_sketch/sketch.proto, line 152 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/5#-MYCeqDGATN-E86CyXgl:-MYCeqDGATN-E86CyXgm:bpe8dlx) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/22db863b507358d15199bb0bd30cc5adeb7c8653/src/main/proto/wfa/any_sketch/sketch.proto#L152)):*
> ```
>   // Resource key.
>   Key key = 1;
> ```

Drop this field, as it's specifically for the CMMS API.


<!-- Sent from Reviewable.io -->

2021-04-14 00:01 UTC, kungfucraig requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/5)* status: all files reviewed, 2 unresolved discussions (waiting on @wangyaopw)

___
*[src/main/proto/wfa/any_sketch/sketch.proto, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/5#-MYCfPuM9cpfF2hhRKV0:-MYCfPuM9cpfF2hhRKV1:b-4xqf3q) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/22db863b507358d15199bb0bd30cc5adeb7c8653/src/main/proto/wfa/any_sketch/sketch.proto#L1)):*
> ```protobuf
> // Copyright 2020 The Cross-Media Measurement Authors
> ```

Put in a "proto" subdirectory?


<!-- Sent from Reviewable.io -->

2021-04-14 00:12 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/5)* status: all files reviewed, 2 unresolved discussions (waiting on @kungfucraig and @wangyaopw)

___
*[src/main/proto/wfa/any_sketch/sketch.proto, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/5#-MYCfPuM9cpfF2hhRKV0:-MYChvoP8gb53pTRYlyl:b-81owvo) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/22db863b507358d15199bb0bd30cc5adeb7c8653/src/main/proto/wfa/any_sketch/sketch.proto#L1)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Put in a "proto" subdirectory?
</blockquote></details>

We're following language-specific trees. It's already in the proto tree (`src/proto/...`).


<!-- Sent from Reviewable.io -->

2021-04-14 00:13 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/5)* status: all files reviewed, 2 unresolved discussions (waiting on @kungfucraig and @wangyaopw)

___
*[src/main/proto/wfa/any_sketch/sketch.proto, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/5#-MYCfPuM9cpfF2hhRKV0:-MYCiHWC1QFND10rIOUy:bw4iqxc) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/22db863b507358d15199bb0bd30cc5adeb7c8653/src/main/proto/wfa/any_sketch/sketch.proto#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We're following language-specific trees. It's already in the proto tree (`src/proto/...`).
</blockquote></details>

Sorry, `src/main/proto/...`


<!-- Sent from Reviewable.io -->

2021-04-14 00:35 UTC, wangyaopw commented
> > The EncryptedSketch.proto and Sketch.proto inside CMMS-api would be
> > deleted.
> 
> encrypted_sketch.proto will still exists in the CMMS API repo as it documents the byte encoding of an encrypted sketch that's used by the API. (The message itself is never used and only consists of a single `bytes` field).
> 
> > Reviewed 11 of 11 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/5#-:-MYCeLhf7ZhsfuURKtaL:b-6c388q)_ status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @wangyaopw)
> 
> _[src/main/proto/wfa/any_sketch/sketch.proto, line 152 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/5#-MYCeqDGATN-E86CyXgl:-MYCeqDGATN-E86CyXgm:bpe8dlx) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/22db863b507358d15199bb0bd30cc5adeb7c8653/src/main/proto/wfa/any_sketch/sketch.proto#L152)):_
> 
> > ```
> >   // Resource key.
> >   Key key = 1;
> > ```
> 
> Drop this field, as it's specifically for the CMMS API.

Done.

Yep, we can keep EncryptedSketch for documentation purpose.

2021-04-14 00:35 UTC, wangyaopw commented
> > _[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/5)_ status: all files reviewed, 2 unresolved discussions (waiting on @wangyaopw)
> 
> _[src/main/proto/wfa/any_sketch/sketch.proto, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/5#-MYCfPuM9cpfF2hhRKV0:-MYCfPuM9cpfF2hhRKV1:b-4xqf3q) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/22db863b507358d15199bb0bd30cc5adeb7c8653/src/main/proto/wfa/any_sketch/sketch.proto#L1)):_
> 
> > ```protobuf
> > // Copyright 2020 The Cross-Media Measurement Authors
> > ```
> 
> Put in a "proto" subdirectory?

Yep, it is already under src/main/proto

2021-04-14 00:55 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/5)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig)



<!-- Sent from Reviewable.io -->

2021-04-14 22:31 UTC, kungfucraig approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/5)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @wangyaopw)

___
*[src/main/proto/wfa/any_sketch/sketch.proto, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/5#-MYCfPuM9cpfF2hhRKV0:-MYHVXrx1QKlbme4kafN:bn8nt70) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/22db863b507358d15199bb0bd30cc5adeb7c8653/src/main/proto/wfa/any_sketch/sketch.proto#L1)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Yep, it is already under src/main/proto
</blockquote></details>

Indeed it is. Not sure how I missed that.


<!-- Sent from Reviewable.io -->

2021-04-14 22:39 UTC, merged